name: Accessibility Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  accessibility-test:
    name: Run Accessibility Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pa11y-ci
      run: npm install -g pa11y-ci pa11y-ci-reporter-html

    - name: Start local server
      run: |
        python3 -m http.server 8000 &
        echo $! > server.pid
        sleep 5

    - name: Test that server is running
      run: |
        curl http://localhost:8000/a.html

    - name: Create pa11y-ci config
      run: |
        cat <<EOF > .pa11yci.json
        {
          "defaults": {
            "timeout": 240000,
            "runners": ["axe"],
            "ignore": ["color-contrast"],
            "concurrency": 1,
            "chromeLaunchConfig": {
              "ignoreHTTPSErrors": true,
              "args": ["--disable-dev-shm-usage", "--no-sandbox"]
            }
          },
          "urls": [
            {
              "url": "http://localhost:8000/a.html"
            }
          ]
        }
        EOF

    - name: Run accessibility tests
      run: |
        pa11y-ci -c .pa11yci.json

    - name: Run accessibility tests with html reporter
      run: |
        pa11y-ci -c .pa11yci.json --reporter=pa11y-ci-reporter-html

    - name: Stop local server
      run: kill $(cat server.pid)

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: accessibility-report
        path: pa11y-ci-report/
